### ISSUE TITLE
Component.AsModel returning malformed Model

### ISSUE THREAD

**Issue by MarkNais** [angelsix/solidworks-api#123]
Still performing triage, but it's getting late.
Goal: Recurse thru an assembly, removing custom-property bloat.
Issue: Using the Component recursive-action added in #47 (by @emersonbottero), I'm trying to cast back to the Model but running into NullRefEx' within Model. Notably the model object exists, but is malformed (seems like an empty object).

```C#
        Application.ActiveModel.Components(CompRemoveProps);
// ... later ...
private void CompRemoveProps(AngelSix.SolidDna.Component comp, int depth){
        if (comp == null) return;
        Model model = comp.AsModel;
        if (model == null) return;
        model.CustomProperties(RemoveExcessiveProperties);  //Errors here.
}
```
https://github.com/angelsix/solidworks-api/blob/19752f8ad1f7ff2e1857d18a7bf0c1b8eb589d4f/SolidDna/AngelSix.SolidDna/SolidWorks/Models/Component/Component.cs#L15

**Comment by brinkdinges** [comment]
I don't know if you fixed this by now, but here's why.

If an assembly has not loaded all of its parts completely, the components are loaded but the models are not. So if you get a model from a component, it will be null. Resolving the assembly fixes this, which is why I always do this before batch tasks like this.

So it's not SolidDna behaving badly, it's default SolidWorks behavior. SolidDna does make it harder the find the reason, though, because the Model object isn't null, but the UnsafeObject is.

**Comment by MarkNais** [comment]
You're quite right, thank you for your response! Suppressed models were the culprit.

And I greatly appreciate your and AngelSix's efforts on this project!
