### ISSUE TITLE
Using external library fails

### ISSUE THREAD

**Issue by billpeet** [angelsix/solidworks-api#55]
I have a basic SolidDNA addin as follows:
```c#
public class Integration : AddInIntegration
{

    // All overrides left blank
    public override void ApplicationStartup()
    {
    }

    public override void ConfigureServices(FrameworkConstruction construction)
    {
    }

    public override void PreConnectToSolidWorks()
    {
    }

    public override void PreLoadPlugIns()
    {
    }
}

public class MySolidDnaPlugin : SolidPlugIn
{
    public override string AddInTitle { get; } = "foo";
    public override string AddInDescription { get; } = "bar";

    public override void ConnectedToSolidWorks()
    {
        // This works fine...
        Boo.Lang.List l = new Boo.Lang.List();

        // ....But this doesn't :(
        Boo.Lang.Compiler.BooCompiler c = new Boo.Lang.Compiler.BooCompiler();
    }

    public override void DisconnectedFromSolidWorks()
    {
    }

}
```
I'm attempting to add support for Boo scripting, to allow users to change the plugin script without needing to recompile.
I've added the NuGet package RhinoDSL, which also adds the references `Boo.Lang`, `Boo.Lang.Compiler` and `Boo.Lang.Parser`. Building the project definitely adds the files Boo.Lang.dll, Boo.Lang.Compiler.dll and Boo.Lang.Parser.dll to the /bin folder.
I'm able to classes in Boo.Lang (see Boo.Lang.List above), but when I try and create anything from the Boo.Lang.Compiler namespace it throw an exception:
`Could not load file or assembly 'Boo.Lang, Version=2.0.9.4, Culture=neutral, PublicKeyToken-32c39770e9a21a67' or one of its dependencies. The system cannot find the file specified.`

Any thoughts?

**Comment by angelsix** [comment]
This is due to the way SolidWorks environment changes where files and satellite assemblies get loaded. I manually patch in the search with to the install folder if run from a new app-domain for a similar issue perhaps you can try something similar to help resolve any dlls https://github.com/angelsix/solidworks-api/blob/develop/SolidDna/AngelSix.SolidDna/SolidWorks/Integration/PlugInIntegration.cs#L92 also make sure they are not marked as embed interop
